
project_id = "jepeeykyoouhaqhondcq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[db.pooler]
port = 54329
shadow_port = 54319

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326
uri_allow_list = ["https://jepeeykyoouhaqhondcq.supabase.co/auth/v1/callback"]

[storage]
enabled = true
port = 54327

[edge_runtime]
enabled = true
port = 54328

[functions]
port = 54328

[functions.processPayout]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

