// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jepeeykyoouhaqhondcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplcGVleWt5b291aGFxaG9uZGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDM0MzYsImV4cCI6MjA2MzIxOTQzNn0.bPKhW7rhWrAqnTnZF6DI6R_1eiSJC6YcfvPQNuLFKlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);