
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tphwebrzhqhwtvuxuyqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwaHdlYnJ6aHFod3R2dXh1eXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzQ2MzksImV4cCI6MjA2Mzc1MDYzOX0.Cl1o4kywEtPdOLdJX5mB3P0yhoROt3U5FxP9DscQwDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Error handling helper
export const handleSupabaseError = (error: any, context?: string) => {
  console.error(`Supabase error ${context ? `in ${context}` : ''}:`, error);
  return error?.message || 'An unexpected error occurred';
};
